第3回課題提出
ChinamiO/Chinami-Risetech pull request #3
Opened 2023-07-22 02:48 UTC by ChinamiO

お世話になっております。
第3回課題提出いたしますので、ご確認お願いいたします。

2023-07-22 04:02 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！
https://github.com/ChinamiO/Chinami-Risetech/pull/3/files

2023-07-22 04:02 UTC, MasatoshiMizumoto commented on lecture03.md
> +##DBサーバーについて
スタイル崩れてます！

2023-07-22 04:02 UTC, MasatoshiMizumoto commented on lecture03.md
> +##Railsの構成管理ツール
ここもスタイル崩れてます！

2023-07-22 04:02 UTC, MasatoshiMizumoto commented on lecture03.md
> +##学んだこと
ここもスタイル崩れてます！

2023-07-22 04:02 UTC, MasatoshiMizumoto commented on lecture03.md
> +　　サンプルアプリケーションを起動するまでの作業は難しかったがうまく起動できると嬉しかった。
段落扱いだとで改行は無視されるので、改行にしたい場合はリストスタイルを使ってください！

2023-07-22 04:02 UTC, MasatoshiMizumoto commented on lecture03.md
> +   - ruby:puma version 5.6.5
インデントする意味がないかなと感じるのでインデントは消して良いかなと思いました！

2023-07-22 08:19 UTC, ChinamiO commented
遅くなり申し訳ございません。
やり直してみたのですが大丈夫でしょうか？

2023-07-22 11:36 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2023-07-22 11:36 UTC, MasatoshiMizumoto commented on lecture03.md
> +   - ruby:pumaversion 5.6.5
インデントいらないと思います！
```suggestion
- ruby:pumaversion 5.6.5
```

2023-07-22 11:36 UTC, MasatoshiMizumoto commented on lecture03.md
> +   - mysqlversion:8.0.34
これもインデントいらないですね！
```suggestion
- mysqlversion:8.0.34
```

2023-07-22 11:36 UTC, MasatoshiMizumoto commented on lecture03.md
MarkdownはYAMLとは違うので、全体的にインデントはいれなくて良いです！
入れるとすればリストスタイルの時だけかと。

あと、証跡としてスクショをこのブランチでpushしてMarkdownで表示させてほしいです。

2023-07-22 11:36 UTC, MasatoshiMizumoto commented on lecture03.md
> +  サンプルアプリケーションを起動するまでの作業は難しかったがうまく起動できると嬉しかった。
```suggestion
情報量が多く混乱したが、アプリケーションを作る際に必要なデータベースやツールなどを学んだ。  
サンプルアプリケーションを起動するまでの作業は難しかったがうまく起動できると嬉しかった。
```

2023-07-22 11:36 UTC, MasatoshiMizumoto commented on lecture03.md
> +   Bundler
```suggestion
Bundler
```

2023-08-03 16:05 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-08-10 12:37 UTC, merged